STATE_MAPPING = {
    "AP": "Andhra Pradesh",
    "AS": "Assam",
    "BR": "Bihar",
    "CG": "Chhattisgarh",
    "DL": "Delhi",
    "GJ": "Gujarat",
    "GO": "Goa",
    "HP": "Himachal Pradesh",
    "HR": "Haryana",
    "JH": "Jharkhand",
    "JK": "Jammu & Kashmir",
    "KA": "Karnataka",
    "KE": "Kerala",
    "MH": "Maharashtra",
    "ML": "Meghalaya",
    "MP": "Madhya Pradesh",
    "OR": "Orissa",
    "PB": "Punjab",
    "PY": "Pondicherry",
    "RJ": "Rajasthan",
    "TN": "Tamil Nadu",
    "TR": "Tripura",
    "UP": "Uttar Pradesh",
    "WB": "West Bengal",
    "TS": "Telangana",
    "KO": "Kolkata"
}
